name: Integration test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Test:
    runs-on: ubuntu-latest
    permissions:
      packages: read
      statuses: write
      checks: write
      contents: read
    container:
      image: ghcr.io/langproc/langproc-cw/environment:latest-2025-26
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Install requirements
        run: |
          apt-get update
          apt-get install -y python3-venv
          python3 -m venv venv
          pip install lit filecheck

      - name: Build and test
        id: test
        timeout-minutes: 1
        shell: bash
        run: |
          source venv/bin/activate
          make test

      - name: Perm issue fix
        if: always()
        run: git config --global --add safe.directory "/__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}"

      - name: Upload test results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Test results
          path: build/lit_out.xml
          reporter: java-junit
          fail-on-error: false
