name: clang-tidy-review

on:
  pull_request:

permissions:
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bison flex

      - name: CMake
        run: cmake -S . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=YES

      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          database: "build"
          style: "file" # Use .clang-format
          tidy-checks: "" # Use .clang-tidy

      # If there are any comments, fail the check
      - if: steps.linter.outputs.clang-tidy-checks-failed > 0
        run: exit 1
